### ISSUE TITLE
apt-get check fails if python is not installed (fails for ubuntu16.04)

### ISSUE THREAD

**Issue by hlawatschek** [nl2go/ansible-role-hetzner_installimage#19]
Check is apt-get installed] **************************************************************************************************************************
fatal: [188.40.128.86]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 188.40.128.86 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

**Comment by dirkaholic** [comment]
Fixed by #20
